[profile.default]
src = 'contracts'
out = 'artifacts'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
optimizer = true
optimizer_runs = 2000
solc_version = '0.8.28'
evm_version = 'cancun'
gas_reports = ['*']
auto_detect_solc = true
offline = false
ignored_error_codes = ["license", "code-size"]

[fuzz]
runs = 256
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true
shrink_sequence = true

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 100
multiline_func_header = "attributes_first"
number_underscore = "thousands"
quote_style = "double"
single_line_statement_blocks = "single"
tab_width = 2
wrap_comments = true
